name = "synesthesai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-29"

[vars]
SYNESTHESAI_FRONTEND_URLS = ["https://synesthesai-react.pages.dev", "https://synesthesai.com", "http://localhost:5173"]

[durable_objects]
bindings = [
  { name = "users", class_name = "User" },
  { name = "tracks", class_name = "Track" },
  { name = "creations", class_name = "Creation" },
]

[[r2_buckets]]
binding = "CREATIONS_BUCKET"
bucket_name = "synesthesai-creations"
preview_bucket_name = "synesthesai-creations-dev"

[[migrations]]
tag = "v1"
new_classes = ["User"]

[[migrations]]
tag = "v2"
new_classes = ["Creation", "Track"]
