name = "synesthesai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-29"

[vars]
SYNESTHESAI_FRONTEND_URLS = ["https://synesthesai-react.pages.dev", "https://synesthesai.com", "http://localhost:5173"]

[[r2_buckets]]
binding = "CREATIONS_BUCKET"
bucket_name = "synesthesai-creations"
preview_bucket_name = "synesthesai-creations-dev"
