name = "synesthesai-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-01-29"

[[r2_buckets]]
binding = "CREATIONS_BUCKET"
bucket_name = "synesthesai-creations"
preview_bucket_name = "synesthesai-creations-dev"
